name: Build an AMI using Packer for Pull Request

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer AMI Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json