name: Build an AMI using Packer

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Packer AMI Build
        uses: hashicorp/packer-github-actions@main
        with:
          command: validate
          args: -syntax-only
          target: ami.json
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        #   AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        #   AMI_USERS: ${{ secrets.AMI_USERS }}
        #   SUBNET_ID: ${{ secrets.SUBNET_ID }}