name: Build an AMI using Packer

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Packer AMI Build
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -syntax-only
          target: ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          # AMI_USERS: ${{ secrets.AMI_USERS }}
          subnet_id: ${{ secrets.INSTANCE_TYPE }}
          source_ami: ${{ secrets.SOURCE_AMI }}